algoritmo "ATIVIDADE 9.11"
 // Disciplina : [Lógica de Programação]
 // Professor : [Rodolfo Clepf]
 // Descrição : Contagem de 10 a 3
 // Autor(a) : Gabriel Junio Borba de Paula
 // Data atual : 07/05/2024
Var
x, c, soma : inteiro



Inicio
c <- 1
enquanto (c <= 7) faca
c <- c + 1
    escreval ("Digite um número:")
    leia (x)
    soma <- soma + x
     
fimenquanto
escreval("A soma dos números é: ", soma)





fimalgoritmo